friend = Friend.create(name: "Rakeeta", location: "Chicago", years: 3)
friend = Friend.create(name: "Kristen", location: "Sweden", years: 15)
friend = Friend.create(name: "Karol", location: "Chicago", years: 1)
friend = Friend.create(name: "Rudi", location: "Bali", years: 15)
friend = Friend.create(name: "Asha", location: "Memphis", years: 10)
friend = Friend.create(name: "Jamesa", location: "Ann Arbor", years: 10)